### ISSUE TITLE
Mocked new_instances are not properly cleaned by teardown in Python 3

### ISSUE THREAD

**Issue by lindycoder** [flexmock/flexmock#16]
Hello!

It would seem that when using `flexmock(<class>).new_instances()` in python 3.4 won't clean the bindings on the class upon calling teardown.

This is an example script using latest flexmock==0.10.2 on Python 3.4.4

```python
from flexmock._api import flexmock, flexmock_teardown


class MyClass:
    def __init__(self, param):
        pass

flexmock(MyClass).new_instances(flexmock())
flexmock_teardown()

obj = MyClass("hehe")

print("All good! :D")

```

Output is 

```
Traceback (most recent call last):
  File "issue.py", line 11, in <module>
    obj = MyClass("hehe")
TypeError: object() takes no parameters
```

If i try to call MyClass without param error becomes

```
Traceback (most recent call last):
  File "issue.py", line 11, in <module>
    obj = MyClass()
TypeError: __init__() missing 1 required positional argument: 'param'
```

It works fine on Python 2.7.11

**Comment by bkabrda** [comment]
Hi, thanks for the report, I'll look into it. It definitely looks like a bug and I can reproduce it.

**Comment by bkabrda** [comment]
So I think you're hitting https://github.com/bkabrda/flexmock/issues/13, which is caused by a bug in Python itself [1]. The weird thing is, I have Python 3.5.2 where this should already be fixed and I'm still getting the error. So either the fix is wrong or there's another problem somewhere. I'll continue investigating.

[1] http://bugs.python.org/issue25731

**Comment by bkabrda** [comment]
So yeah, the fix for the underlying Python issue has been reverted. I have a feeling that it was reverted by mistake, but I'm not completely sure. I left a comment at the issue, so we'll see [1].

[1] http://bugs.python.org/issue25731#msg278962

**Comment by wojtha** [comment]
We just run into this issue in 2022. @bkabrda seems that your voice in the related Python issue in 2016 wasn't heard ☹️ I suggest we should raise a warning when `new_instances()` is called until the issue is resolved. Or perhaps make a note about it in the documentation.

**Comment by ollipa** [comment]
@wojtha, thank you for your suggestions. I added a warning to the documentation in PR #127. I think before we raise a warning when `new_instances` method is called, we should first think about some alternative way to fake new instances.

As a side note, this bug seems to only affect CPython. For example, PyPy doesn't suffer from this bug.

**Comment by christophe-riolo** [comment]
We should probably follow up on the Python bug tracker also, it's tricky to fix this bug without this :thinking:

**Comment by LecrisUT** [comment]
What's the status on this in 2024. From what I manage to read on the issue it should only affect if you manually call `felxmock_teardown`, and not something like providing `n` new_instances but being called `n+1` times?

**Comment by ollipa** [comment]
I don't think anything has changed. The issue still exists in CPython.
